=== Copenhagen-Alliance/versification-specification/versification-mappings/json-schema/versification_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://burrito.bible/schema/ingredients/versification.schema.json",
  "$$target": "canon_constraints.schema.json",
  "title": "Canon Constraints",
  "type": "object",
  "definitions": {
    "bcv": {
      "type": "string",
      "pattern": "^[A-Z1-6]{3} [0-9]+:[0-9]+$"
    },
    "bcvRange": {
      "type": "string",
      "pattern": "^[A-Z1-6]{3} [0-9]+:[0-9]+(-[0-9]+)?$"
    },
    "bookName": {
      "type": "string",
      "pattern": "^[A-Z1-6]{3}$"
    }
  },
  "properties": {
    "basedOn": {
      "type": "string",
      "pattern": "^[a-z][a-z0-9]*"
    },
    "verification": {
      "type": "array",
      "items": {
        "properties": {
          "tool": {
            "type": "string"
          },
          "timestamp": {
            "type": "string",
            "format": "date-time"
          },
          "passed": {
            "type": "boolean"
          },
          "report": {}
        },
        "required": ["tool", "passed"]
      },
      "additionalProperties": false
    },
    "maxVerses": {
      "type": "object",
      "propertyNames": {
        "$ref": "#/definitions/bookName"
      },
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "number",
          "minimum": 0,
          "multipleOf": 1.0
        },
        "additionalItems": false
      }
    },
    "excludedVerses": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/bcv"
      },
      "additionalItems": false
    },
    "mappedVerses": {
      "type": "object",
      "propertyNames": {
        "$ref": "#/definitions/bcvRange"
      },
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/bcvRange"
        },
        "additionalItems": false
      }
    },
    "mergedVerses": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/bcvRange"
      },
      "additionalItems": false
    },
    "partialVerses": {
      "type": "object",
      "propertyNames": {
        "$ref": "#/definitions/bcv"
      },
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        },
        "additionalItems": false
      }
    }
  },
  "required": ["maxVerses"],
  "additionalProperties": false
}

=== Copenhagen-Alliance/versification-specification/versification-mappings/sample-custom-mappings/validated.json
{
  "verification": [
    {
      "tool": "myCoolVersificationizer v0.0.3",
      "passed": true
    },
    {
      "tool": "hisMeanVersificationizer",
      "passed": false,
      "timestamp": "2019-02-19T01:02:03+01:00",
      "report": {
        "some": "unspecified",
        "wholesome": ["goodness", "to", "contemplate"]
      }
    }
  ],
  "partialVerses": {
    "SIR 36:13": ["a"],
    "SIR 36:16": ["b"]
  },
  "excludedVerses": [
    "ISA 41:6",
    "ISA 41:7",
    "ACT 24:7",
    "ACT 28:29",
    "ROM 16:24",
    "TOB 5:23",
    "TOB 6:19",
    "TOB 10:14",
    "TOB 11:19",
    "ESG 4:6",
    "ESG 9:5",
    "ESG 9:32",
    "SIR 36:14",
    "SIR 36:15",
    "SIR 36:16",
    "SIR 41:23",
    "SIR 41:24",
    "SIR 41:25",
    "SIR 41:26",
    "SIR 41:27",
    "DAG 3:1",
    "DAG 3:2",
    "DAG 3:3",
    "DAG 3:4",
    "DAG 3:5",
    "DAG 3:6",
    "DAG 3:7",
    "DAG 3:8",
    "DAG 3:9",
    "DAG 3:10",
    "DAG 3:11",
    "DAG 3:12",
    "DAG 3:13",
    "DAG 3:14",
    "DAG 3:15",
    "DAG 3:16",
    "DAG 3:17",
    "DAG 3:18",
    "DAG 3:19",
    "DAG 3:20",
    "DAG 3:21",
    "DAG 3:22",
    "DAG 3:23",
    "4MA 10:4",
    "4MA 11:7",
    "4MA 11:8",
    "1ES 2:26",
    "1ES 3:24",
    "1ES 5:71"
  ],
  "maxVerses": {
    "JOS": [
      18, 24, 17, 24, 15, 27, 26, 35, 27, 43, 23, 24, 33, 15, 63, 10, 18, 28,
      51, 9, 45, 34, 16, 33
    ],
    "BLT": [42],
    "JON": [16, 11, 10, 11],
    "JSA": [
      18, 24, 17, 24, 15, 27, 26, 35, 27, 43, 23, 24, 33, 15, 63, 10, 18, 28,
      51, 9, 45, 34, 16, 33
    ],
    "NEH": [11, 20, 38, 17, 19, 19, 72, 18, 37, 40, 36, 47, 31],
    "TIT": [16, 15, 15],
    "REV": [
      20, 29, 22, 11, 14, 17, 17, 13, 21, 11, 19, 18, 18, 20, 8, 21, 18, 24, 21,
      15, 27, 21
    ],
    "PHM": [25],
    "4MA": [
      35, 24, 21, 26, 38, 35, 23, 29, 32, 21, 27, 19, 27, 20, 32, 25, 24, 24
    ],
    "LJE": [72],
    "ISA": [
      31, 22, 26, 6, 30, 13, 25, 23, 20, 34, 16, 6, 22, 32, 9, 14, 14, 7, 25, 6,
      17, 25, 18, 23, 12, 21, 13, 29, 24, 33, 9, 20, 24, 17, 10, 22, 38, 22, 8,
      31, 29, 25, 28, 28, 25, 13, 15, 22, 26, 11, 23, 15, 12, 17, 13, 12, 21,
      14, 21, 22, 11, 12, 19, 11, 25, 24
    ],
    "HAG": [15, 23],
    "ZEC": [17, 17, 10, 14, 11, 15, 14, 23, 17, 12, 17, 14, 9, 21],
    "1SA": [
      28, 36, 21, 22, 12, 21, 17, 22, 27, 27, 15, 25, 23, 52, 35, 23, 58, 30,
      24, 42, 16, 23, 28, 23, 44, 25, 12, 25, 11, 31, 13
    ],
    "EZK": [
      28, 10, 27, 17, 17, 14, 27, 18, 11, 22, 25, 28, 23, 23, 8, 63, 24, 32, 14,
      44, 37, 31, 49, 27, 17, 21, 36, 26, 21, 26, 18, 32, 33, 31, 15, 38, 28,
      23, 29, 49, 26, 20, 27, 31, 25, 24, 23, 35
    ],
    "DAN": [21, 49, 33, 34, 30, 29, 28, 27, 27, 21, 45, 13],
    "EZA": [36, 52, 56, 59, 139, 63, 47, 60, 46, 51, 58, 48],
    "MAT": [
      25, 23, 17, 25, 48, 34, 29, 34, 38, 42, 30, 50, 58, 36, 39, 28, 27, 35,
      30, 34, 46, 46, 39, 51, 46, 75, 66, 20
    ],
    "TBS": [22, 14, 17, 21, 23, 19, 17, 21, 6, 14, 19, 22, 18, 15],
    "ROM": [32, 29, 31, 25, 21, 23, 25, 39, 33, 21, 36, 21, 14, 23, 33, 27],
    "JDG": [
      36, 23, 31, 24, 31, 40, 25, 35, 57, 18, 40, 15, 25, 20, 20, 31, 13, 31,
      30, 48, 25
    ],
    "SUS": [64],
    "3MA": [29, 33, 30, 21, 51, 41, 23],
    "SST": [64],
    "2TI": [18, 26, 17, 22],
    "DEU": [
      46, 37, 29, 49, 33, 25, 26, 20, 29, 22, 32, 31, 19, 29, 23, 22, 20, 22,
      21, 20, 23, 29, 26, 22, 19, 19, 26, 69, 28, 20, 30, 52, 29, 12
    ],
    "1ES": [55, 26, 24, 63, 71, 33, 15, 92, 55],
    "HAB": [17, 20, 19],
    "JOB": [
      22, 13, 26, 21, 27, 30, 21, 22, 35, 22, 20, 25, 28, 22, 35, 22, 16, 21,
      29, 29, 34, 30, 17, 25, 6, 14, 23, 28, 25, 31, 40, 22, 33, 37, 16, 33, 24,
      41, 30, 32, 26, 17
    ],
    "SNG": [17, 17, 11, 16, 16, 12, 14, 14],
    "EXO": [
      22, 25, 22, 31, 23, 30, 29, 28, 35, 29, 10, 51, 22, 31, 27, 36, 16, 27,
      25, 26, 37, 30, 33, 18, 40, 37, 21, 43, 46, 38, 18, 35, 23, 35, 35, 38,
      29, 31, 43, 38
    ],
    "JHN": [
      51, 25, 36, 54, 47, 71, 53, 59, 41, 42, 57, 50, 38, 31, 27, 33, 26, 40,
      42, 31, 25
    ],
    "PRO": [
      33, 22, 35, 27, 23, 35, 27, 36, 18, 32, 31, 28, 25, 35, 33, 33, 28, 24,
      29, 30, 31, 29, 35, 34, 28, 28, 27, 28, 27, 33, 31
    ],
    "ESG": [39, 23, 22, 47, 28, 14, 10, 41, 32, 14],
    "WIS": [
      16, 24, 19, 20, 23, 25, 30, 21, 18, 21, 26, 27, 19, 31, 19, 29, 21, 25, 22
    ],
    "DAG": [64, 42, 90],
    "JOL": [20, 27, 5, 21],
    "EZR": [11, 70, 13, 24, 17, 22, 28, 36, 15, 44],
    "3JN": [15],
    "ENO": [
      28, 42, 30, 88, 40, 42, 39, 46, 42, 16, 19, 40, 34, 35, 45, 41, 69, 42,
      29, 53, 57, 14, 26, 16, 30, 37, 21, 34, 28, 23, 29, 82, 59, 49, 36, 30,
      34, 36, 24, 40, 22, 16
    ],
    "DNT": [21, 49, 97, 37, 30, 29, 28, 27, 27, 21, 45, 13],
    "NUM": [
      54, 34, 51, 49, 31, 27, 89, 26, 23, 36, 35, 16, 33, 45, 41, 35, 28, 32,
      22, 29, 35, 41, 30, 25, 19, 65, 23, 31, 39, 17, 54, 42, 56, 29, 34, 13
    ],
    "HEB": [14, 18, 19, 16, 14, 20, 28, 13, 28, 39, 40, 29, 25],
    "S3Y": [67],
    "ZEP": [18, 15, 20],
    "PHP": [30, 30, 21, 23],
    "PSA": [
      6, 12, 9, 9, 13, 11, 18, 10, 21, 18, 7, 9, 6, 7, 5, 11, 15, 51, 15, 10,
      14, 32, 6, 10, 22, 12, 14, 9, 11, 13, 25, 11, 22, 23, 28, 13, 40, 23, 14,
      18, 14, 12, 5, 27, 18, 12, 10, 15, 21, 23, 21, 11, 7, 9, 24, 14, 12, 12,
      18, 14, 9, 13, 12, 11, 14, 20, 8, 36, 37, 6, 24, 20, 28, 23, 11, 13, 21,
      72, 13, 20, 17, 8, 19, 13, 14, 17, 7, 19, 53, 17, 16, 16, 5, 23, 11, 13,
      12, 9, 9, 5, 8, 29, 22, 35, 45, 48, 43, 14, 31, 7, 10, 10, 9, 8, 18, 19,
      2, 29, 176, 7, 8, 9, 4, 8, 5, 6, 5, 6, 8, 8, 3, 18, 3, 3, 21, 26, 9, 8,
      24, 14, 10, 8, 12, 15, 21, 10, 20, 14, 9, 6
    ],
    "OBA": [21],
    "PS2": [7],
    "2KI": [
      18, 25, 27, 44, 27, 33, 20, 29, 37, 36, 20, 22, 25, 29, 38, 20, 41, 37,
      37, 21, 26, 20, 37, 20, 30
    ],
    "BEL": [42],
    "ECC": [18, 26, 22, 17, 19, 12, 29, 17, 18, 20, 10, 14],
    "EST": [22, 23, 15, 17, 14, 14, 10, 17, 32, 3],
    "1TH": [10, 20, 13, 18, 28],
    "ODA": [19, 43, 10, 19, 12, 8, 20, 37, 22, 9, 11, 15, 4, 46],
    "1PE": [25, 25, 22, 19, 14],
    "JUB": [
      26, 17, 19, 24, 36, 34, 37, 40, 27, 48, 39, 56, 34, 55, 20, 28, 30, 31,
      59, 66, 30, 38, 59, 30, 50, 48, 37, 38, 27, 29, 31, 24, 30, 20
    ],
    "COL": [29, 23, 25, 18],
    "1KI": [
      53, 46, 28, 20, 32, 38, 51, 66, 28, 29, 43, 33, 34, 31, 34, 34, 24, 46,
      21, 43, 29, 54
    ],
    "2CH": [
      18, 17, 17, 22, 14, 42, 22, 18, 31, 19, 23, 16, 23, 14, 19, 14, 19, 34,
      11, 37, 20, 12, 21, 27, 28, 23, 9, 27, 36, 27, 21, 33, 25, 33, 27, 23
    ],
    "EPH": [23, 22, 21, 32, 33, 24],
    "JAS": [27, 26, 18, 17, 20],
    "JDB": [
      36, 23, 31, 24, 31, 40, 25, 35, 57, 18, 40, 15, 25, 20, 20, 31, 13, 31,
      30, 48, 25
    ],
    "SIR": [
      30, 18, 31, 31, 15, 37, 36, 19, 18, 31, 34, 18, 26, 27, 20, 30, 32, 33,
      30, 31, 28, 27, 28, 34, 26, 29, 30, 26, 28, 25, 31, 24, 33, 31, 26, 31,
      31, 34, 35, 30, 27, 25, 33, 23, 26, 20, 25, 25, 16, 29, 30
    ],
    "GEN": [
      31, 25, 24, 26, 32, 22, 24, 22, 29, 32, 32, 20, 18, 24, 21, 16, 27, 33,
      38, 18, 34, 24, 20, 67, 34, 35, 46, 22, 35, 43, 54, 33, 20, 31, 29, 43,
      36, 30, 23, 23, 57, 38, 34, 34, 28, 34, 31, 22, 33, 26
    ],
    "2JN": [13],
    "PSS": [8, 37, 12, 25, 19, 6, 10, 34, 11, 8, 9, 6, 12, 10, 13, 15, 46, 12],
    "AMO": [15, 16, 15, 13, 27, 14, 17, 14, 15],
    "BAR": [22, 35, 38, 37, 9],
    "2MA": [36, 32, 40, 50, 27, 31, 42, 36, 29, 38, 38, 45, 26, 46, 39],
    "JER": [
      19, 37, 25, 31, 31, 30, 34, 23, 25, 25, 23, 17, 27, 22, 21, 21, 27, 23,
      15, 18, 14, 30, 40, 10, 38, 24, 22, 17, 32, 24, 40, 44, 26, 22, 19, 32,
      21, 28, 18, 16, 18, 22, 13, 30, 5, 28, 7, 47, 39, 46, 64, 34
    ],
    "2TH": [12, 17, 18],
    "LAM": [22, 22, 66, 22, 22],
    "JDT": [16, 28, 10, 15, 24, 21, 32, 36, 14, 23, 23, 20, 20, 19, 14, 25],
    "1JN": [10, 29, 24, 21, 21],
    "MRK": [45, 28, 35, 41, 43, 56, 37, 38, 50, 52, 33, 44, 37, 72, 47, 20],
    "GAL": [24, 21, 29, 31, 26, 18],
    "2CO": [24, 17, 18, 18, 21, 18, 16, 24, 15, 18, 33, 21, 13],
    "2SA": [
      27, 32, 39, 12, 25, 23, 29, 18, 13, 19, 27, 31, 39, 33, 37, 23, 29, 32,
      44, 26, 22, 51, 39, 25
    ],
    "1MA": [64, 70, 60, 61, 68, 63, 50, 32, 73, 89, 74, 53, 53, 49, 41, 24],
    "LUK": [
      80, 52, 38, 44, 39, 49, 50, 56, 62, 42, 54, 59, 35, 35, 32, 31, 37, 43,
      48, 47, 38, 71, 56, 53
    ],
    "1CH": [
      54, 55, 24, 43, 41, 66, 40, 40, 44, 14, 47, 41, 14, 17, 29, 43, 27, 17,
      19, 8, 30, 19, 32, 31, 31, 32, 34, 21, 30
    ],
    "RUT": [22, 23, 18, 22],
    "JUD": [25],
    "MIC": [16, 13, 12, 14, 14, 16, 20],
    "ACT": [
      26, 47, 26, 37, 42, 15, 60, 40, 43, 48, 30, 25, 52, 28, 41, 40, 34, 28,
      40, 38, 40, 30, 35, 27, 27, 32, 44, 31
    ],
    "MAN": [15],
    "1TI": [20, 15, 16, 16, 25, 21],
    "2PE": [21, 22, 18],
    "NAM": [14, 14, 19],
    "LEV": [
      17, 16, 17, 35, 26, 23, 38, 36, 24, 20, 47, 8, 59, 57, 33, 34, 16, 30, 37,
      27, 24, 33, 44, 23, 55, 46, 34
    ],
    "1CO": [31, 16, 23, 21, 13, 20, 40, 13, 27, 33, 34, 31, 13, 40, 58, 24],
    "TOB": [22, 14, 17, 21, 22, 18, 17, 21, 6, 13, 18, 22, 18, 15],
    "HOS": [9, 25, 5, 19, 15, 11, 16, 14, 17, 15, 11, 15, 15, 10],
    "MAL": [14, 17, 24],
    "2ES": [40, 48, 36, 52, 56, 59, 140, 63, 47, 59, 46, 51, 58, 48, 63, 78]
  },
  "mappedVerses": {
    "SIR 34:19-22": ["SIR 34:16-19"],
    "SIR 34:16-18": ["SIR 34:14-16"],
    "DAG 1:1-64": ["SUS 1:1-64"],
    "SIR 36:17-22": ["SIR 36:11-16"],
    "SIR 42:1": ["SIR 41:26"],
    "DAG 2:1-42": ["BEL 1:1-42"],
    "S3Y 1:37": ["DAG 3:58"],
    "S3Y 1:38-68": ["DAG 3:60-90"],
    "S3Y 1:34-35": ["DAG 3:56-57"],
    "SIR 35:3-4": ["SIR 35:2-3"],
    "SIR 35:24-26": ["SIR 35:22-24"],
    "SIR 41:22": ["SIR 41:24"],
    "TOB 11:18": ["TOB 11:18"],
    "TOB 10:12": ["TOB 10:12"],
    "SIR 35:5-7": ["SIR 35:3-5"],
    "TOB 6:1": ["TOB 5:23"],
